#pragma once

struct PokedexEntry
{
    /*0x00*/ u8 categoryName[12];
    /*0x0C*/ u16 height; //in decimeters
    /*0x0E*/ u16 weight; //in hectograms
    /*0x10*/ const u8* description;
    /*0x14*/ const u8* unusedDescription;
    /*0x18*/ u16 unused;
    /*0x1A*/ u16 pokemonScale;
    /*0x1C*/ u16 pokemonOffset;
    /*0x1E*/ u16 trainerScale;
    /*0x20*/ u16 trainerOffset;
	/*0x22*/ u16 unused2;
};  /*size = 0x24*/

struct AlternateDexEntries
{
	u16 species;
	const u8* description;
};

struct ListMenuItem
{
    const u8* name;
    s32 id;
};

struct PokedexScreenData
{
    u8 field_00;
    u8 field_01;
    u8 field_02;
    u8 field_03;
    u8 field_04;
    u32 field_08;
    u32 field_0C;
    u16 field_10;
    u16 field_12;
    u8 field_14;
    u8 field_15;
    u8 field_16;
    u8 field_17;
    u16 field_18[0x4];
    u8 field_20[0x4];
    u8 field_24[0x4];
    u8 field_28;
    u8 field_29;
    u8 field_2A;
    u8 field_2B;
    u8 field_2C;
    u8 field_2D;
    u8 field_2E;
    u8 field_2F;
    u32 field_30;
    u16 field_34;
    u16 field_36;
    u16 field_38;
    u16 field_3A;
    u16 field_3C;
    u16 field_3E;
    u8 field_40;
    u8 field_41;
    u8 field_42;
    struct ListMenuItem* listItem;
    u16 field_48;
    u8 field_4A[0x10];
    u16 field_5A;
    u16 * field_5C;
    u8 field_60;
    u8 field_61;
    u16 field_62;
    u8 field_64;
    u16 field_66;
    u16 field_68;
    u16 field_6A;
    u16 field_6C;
};

extern struct PokedexScreenData* gPokedexScreenDataPtr;

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

//Kanto
#define NATIONAL_DEX_NONE 0
#define NATIONAL_DEX_BULBASAUR 1
#define NATIONAL_DEX_IVYSAUR 2
#define NATIONAL_DEX_VENUSAUR 3
#define NATIONAL_DEX_CHARMANDER 4
#define NATIONAL_DEX_CHARMELEON 5
#define NATIONAL_DEX_CHARIZARD 6
#define NATIONAL_DEX_SQUIRTLE 7
#define NATIONAL_DEX_WARTORTLE 8
#define NATIONAL_DEX_BLASTOISE 9
#define NATIONAL_DEX_CATERPIE 10
#define NATIONAL_DEX_METAPOD 11
#define NATIONAL_DEX_BUTTERFREE 12
#define NATIONAL_DEX_WEEDLE 13
#define NATIONAL_DEX_KAKUNA 14
#define NATIONAL_DEX_BEEDRILL 15
#define NATIONAL_DEX_PIDGEY 16
#define NATIONAL_DEX_PIDGEOTTO 17
#define NATIONAL_DEX_PIDGEOT 18
#define NATIONAL_DEX_RATTATA 19
#define NATIONAL_DEX_RATICATE 20
#define NATIONAL_DEX_SPEAROW 21
#define NATIONAL_DEX_FEAROW 22
#define NATIONAL_DEX_EKANS 23
#define NATIONAL_DEX_ARBOK 24
#define NATIONAL_DEX_PICHU 25
#define NATIONAL_DEX_PIKACHU 26
#define NATIONAL_DEX_RAICHU 27
#define NATIONAL_DEX_SANDSHREW 28
#define NATIONAL_DEX_SANDSLASH 29
#define NATIONAL_DEX_NIDORAN_F 30
#define NATIONAL_DEX_NIDORINA 31
#define NATIONAL_DEX_NIDOQUEEN 32
#define NATIONAL_DEX_NIDORAN_M 33
#define NATIONAL_DEX_NIDORINO 34
#define NATIONAL_DEX_NIDOKING 35
#define NATIONAL_DEX_CLEFFA 36
#define NATIONAL_DEX_CLEFAIRY 37
#define NATIONAL_DEX_CLEFABLE 38
#define NATIONAL_DEX_VULPIX 39
#define NATIONAL_DEX_NINETALES 40
#define NATIONAL_DEX_IGGLYBUFF 41
#define NATIONAL_DEX_JIGGLYPUFF 42
#define NATIONAL_DEX_WIGGLYTUFF 43
#define NATIONAL_DEX_ZUBAT 44
#define NATIONAL_DEX_GOLBAT 45
#define NATIONAL_DEX_CROBAT 46
#define NATIONAL_DEX_ODDISH 47
#define NATIONAL_DEX_GLOOM 48
#define NATIONAL_DEX_VILEPLUME 49
#define NATIONAL_DEX_BELLOSSOM 50
#define NATIONAL_DEX_PARAS 51
#define NATIONAL_DEX_PARASECT 52
#define NATIONAL_DEX_VENONAT 53
#define NATIONAL_DEX_VENOMOTH 54
#define NATIONAL_DEX_DIGLETT 55
#define NATIONAL_DEX_DUGTRIO 56
#define NATIONAL_DEX_MEOWTH 57
#define NATIONAL_DEX_PERSIAN 58
#define NATIONAL_DEX_PERRSERKER 59
#define NATIONAL_DEX_PSYDUCK 60
#define NATIONAL_DEX_GOLDUCK 61
#define NATIONAL_DEX_MANKEY 62
#define NATIONAL_DEX_PRIMEAPE 63
#define NATIONAL_DEX_GROWLITHE 64
#define NATIONAL_DEX_ARCANINE 65
#define NATIONAL_DEX_POLIWAG 66
#define NATIONAL_DEX_POLIWHIRL 67
#define NATIONAL_DEX_POLIWRATH 68
#define NATIONAL_DEX_POLITOED 69
#define NATIONAL_DEX_ABRA 70
#define NATIONAL_DEX_KADABRA 71
#define NATIONAL_DEX_ALAKAZAM 72
#define NATIONAL_DEX_MACHOP 73
#define NATIONAL_DEX_MACHOKE 74
#define NATIONAL_DEX_MACHAMP 75
#define NATIONAL_DEX_BELLSPROUT 76
#define NATIONAL_DEX_WEEPINBELL 77
#define NATIONAL_DEX_VICTREEBEL 78
#define NATIONAL_DEX_TENTACOOL 79
#define NATIONAL_DEX_TENTACRUEL 80
#define NATIONAL_DEX_GEODUDE 81
#define NATIONAL_DEX_GRAVELER 82
#define NATIONAL_DEX_GOLEM 83
#define NATIONAL_DEX_PONYTA 84
#define NATIONAL_DEX_RAPIDASH 85
#define NATIONAL_DEX_SLOWPOKE 86
#define NATIONAL_DEX_SLOWBRO 87
#define NATIONAL_DEX_SLOWKING 88
#define NATIONAL_DEX_MAGNEMITE 89
#define NATIONAL_DEX_MAGNETON 90
#define NATIONAL_DEX_MAGNEZONE 91
#define NATIONAL_DEX_FARFETCHD 92
#define NATIONAL_DEX_SIRFETCHD 93
#define NATIONAL_DEX_DODUO 94
#define NATIONAL_DEX_DODRIO 95
#define NATIONAL_DEX_SEEL 96
#define NATIONAL_DEX_DEWGONG 97
#define NATIONAL_DEX_GRIMER 98
#define NATIONAL_DEX_MUK 99
#define NATIONAL_DEX_SHELLDER 100
#define NATIONAL_DEX_CLOYSTER 101
#define NATIONAL_DEX_GASTLY 102
#define NATIONAL_DEX_HAUNTER 103
#define NATIONAL_DEX_GENGAR 104
#define NATIONAL_DEX_ONIX 105
#define NATIONAL_DEX_STEELIX 106
#define NATIONAL_DEX_DROWZEE 107
#define NATIONAL_DEX_HYPNO 108
#define NATIONAL_DEX_KRABBY 109
#define NATIONAL_DEX_KINGLER 110
#define NATIONAL_DEX_VOLTORB 111
#define NATIONAL_DEX_ELECTRODE 112
#define NATIONAL_DEX_EXEGGCUTE 113
#define NATIONAL_DEX_EXEGGUTOR 114
#define NATIONAL_DEX_CUBONE 115
#define NATIONAL_DEX_MAROWAK 116
#define NATIONAL_DEX_TYROGUE 117
#define NATIONAL_DEX_HITMONLEE 118
#define NATIONAL_DEX_HITMONCHAN 119
#define NATIONAL_DEX_HITMONTOP 120
#define NATIONAL_DEX_LICKITUNG 121
#define NATIONAL_DEX_LICKILICKY 122
#define NATIONAL_DEX_KOFFING 123
#define NATIONAL_DEX_WEEZING 124
#define NATIONAL_DEX_RHYHORN 125
#define NATIONAL_DEX_RHYDON 126
#define NATIONAL_DEX_RHYPERIOR 127
#define NATIONAL_DEX_HAPPINY 128
#define NATIONAL_DEX_CHANSEY 129
#define NATIONAL_DEX_BLISSEY 130
#define NATIONAL_DEX_TANGELA 131
#define NATIONAL_DEX_TANGROWTH 132
#define NATIONAL_DEX_KANGASKHAN 133
#define NATIONAL_DEX_HORSEA 134
#define NATIONAL_DEX_SEADRA 135
#define NATIONAL_DEX_KINGDRA 136
#define NATIONAL_DEX_GOLDEEN 137
#define NATIONAL_DEX_SEAKING 138
#define NATIONAL_DEX_STARYU 139
#define NATIONAL_DEX_STARMIE 140
#define NATIONAL_DEX_MIME_JR 141
#define NATIONAL_DEX_MR_MIME 142
#define NATIONAL_DEX_MR_RIME 143
#define NATIONAL_DEX_SCYTHER 144
#define NATIONAL_DEX_SCIZOR 145
#define NATIONAL_DEX_SMOOCHUM 146
#define NATIONAL_DEX_JYNX 147
#define NATIONAL_DEX_ELEKID 148
#define NATIONAL_DEX_ELECTABUZZ 149
#define NATIONAL_DEX_ELECTIVIRE 150
#define NATIONAL_DEX_MAGBY 151
#define NATIONAL_DEX_MAGMAR 152
#define NATIONAL_DEX_MAGMORTAR 153
#define NATIONAL_DEX_PINSIR 154
#define NATIONAL_DEX_TAUROS 155
#define NATIONAL_DEX_MAGIKARP 156
#define NATIONAL_DEX_GYARADOS 157
#define NATIONAL_DEX_LAPRAS 158
#define NATIONAL_DEX_DITTO 159
#define NATIONAL_DEX_EEVEE 160
#define NATIONAL_DEX_VAPOREON 161
#define NATIONAL_DEX_JOLTEON 162
#define NATIONAL_DEX_FLAREON 163
#define NATIONAL_DEX_ESPEON 164
#define NATIONAL_DEX_UMBREON 165
#define NATIONAL_DEX_LEAFEON 166
#define NATIONAL_DEX_GLACEON 167
#define NATIONAL_DEX_SYLVEON 168
#define NATIONAL_DEX_PORYGON 169
#define NATIONAL_DEX_PORYGON2 170
#define NATIONAL_DEX_PORYGON_Z 171
#define NATIONAL_DEX_OMANYTE 172
#define NATIONAL_DEX_OMASTAR 173
#define NATIONAL_DEX_KABUTO 174
#define NATIONAL_DEX_KABUTOPS 175
#define NATIONAL_DEX_AERODACTYL 176
#define NATIONAL_DEX_MUNCHLAX 177
#define NATIONAL_DEX_SNORLAX 178
#define NATIONAL_DEX_ARTICUNO 179
#define NATIONAL_DEX_ZAPDOS 180
#define NATIONAL_DEX_MOLTRES 181
#define NATIONAL_DEX_DRATINI 182
#define NATIONAL_DEX_DRAGONAIR 183
#define NATIONAL_DEX_DRAGONITE 184
#define NATIONAL_DEX_MEWTWO 185
#define NATIONAL_DEX_MEW 186
#define NATIONAL_DEX_CHIKORITA 187
#define NATIONAL_DEX_BAYLEEF 188
#define NATIONAL_DEX_MEGANIUM 189
#define NATIONAL_DEX_CYNDAQUIL 190
#define NATIONAL_DEX_QUILAVA 191
#define NATIONAL_DEX_TYPHLOSION 192
#define NATIONAL_DEX_TOTODILE 193
#define NATIONAL_DEX_CROCONAW 194
#define NATIONAL_DEX_FERALIGATR 195
#define NATIONAL_DEX_SENTRET 196
#define NATIONAL_DEX_FURRET 197
#define NATIONAL_DEX_HOOTHOOT 198
#define NATIONAL_DEX_NOCTOWL 199
#define NATIONAL_DEX_LEDYBA 200
#define NATIONAL_DEX_LEDIAN 201
#define NATIONAL_DEX_SPINARAK 202
#define NATIONAL_DEX_ARIADOS 203
#define NATIONAL_DEX_CHINCHOU 204
#define NATIONAL_DEX_LANTURN 205
#define NATIONAL_DEX_TOGEPI 206
#define NATIONAL_DEX_TOGETIC 207
#define NATIONAL_DEX_TOGEKISS 208
#define NATIONAL_DEX_NATU 209
#define NATIONAL_DEX_XATU 210
#define NATIONAL_DEX_MAREEP 211
#define NATIONAL_DEX_FLAAFFY 212
#define NATIONAL_DEX_AMPHAROS 213
#define NATIONAL_DEX_AZURILL 214
#define NATIONAL_DEX_MARILL 215
#define NATIONAL_DEX_AZUMARILL 216
#define NATIONAL_DEX_BONSLY 217
#define NATIONAL_DEX_SUDOWOODO 218
#define NATIONAL_DEX_HOPPIP 219
#define NATIONAL_DEX_SKIPLOOM 220
#define NATIONAL_DEX_JUMPLUFF 221
#define NATIONAL_DEX_AIPOM 222
#define NATIONAL_DEX_AMBIPOM 223
#define NATIONAL_DEX_SUNKERN 224
#define NATIONAL_DEX_SUNFLORA 225
#define NATIONAL_DEX_YANMA 226
#define NATIONAL_DEX_YANMEGA 227
#define NATIONAL_DEX_WOOPER 228
#define NATIONAL_DEX_QUAGSIRE 229
#define NATIONAL_DEX_MURKROW 230
#define NATIONAL_DEX_HONCHKROW 231
#define NATIONAL_DEX_MISDREAVUS 232
#define NATIONAL_DEX_MISMAGIUS 233
#define NATIONAL_DEX_UNOWN 234
#define NATIONAL_DEX_WYNAUT 235
#define NATIONAL_DEX_WOBBUFFET 236
#define NATIONAL_DEX_GIRAFARIG 237
#define NATIONAL_DEX_PINECO 238
#define NATIONAL_DEX_FORRETRESS 239
#define NATIONAL_DEX_DUNSPARCE 240
#define NATIONAL_DEX_GLIGAR 241
#define NATIONAL_DEX_GLISCOR 242
#define NATIONAL_DEX_SNUBBULL 243
#define NATIONAL_DEX_GRANBULL 244
#define NATIONAL_DEX_QWILFISH 245
#define NATIONAL_DEX_SHUCKLE 246
#define NATIONAL_DEX_HERACROSS 247
#define NATIONAL_DEX_SNEASEL 248
#define NATIONAL_DEX_WEAVILE 249
#define NATIONAL_DEX_TEDDIURSA 250
#define NATIONAL_DEX_URSARING 251
#define NATIONAL_DEX_SLUGMA 252
#define NATIONAL_DEX_MAGCARGO 253
#define NATIONAL_DEX_SWINUB 254
#define NATIONAL_DEX_PILOSWINE 255
#define NATIONAL_DEX_MAMOSWINE 256
#define NATIONAL_DEX_CORSOLA 257
#define NATIONAL_DEX_CURSOLA 258
#define NATIONAL_DEX_REMORAID 259
#define NATIONAL_DEX_OCTILLERY 260
#define NATIONAL_DEX_DELIBIRD 261
#define NATIONAL_DEX_MANTYKE 262
#define NATIONAL_DEX_MANTINE 263
#define NATIONAL_DEX_SKARMORY 264
#define NATIONAL_DEX_HOUNDOUR 265
#define NATIONAL_DEX_HOUNDOOM 266
#define NATIONAL_DEX_PHANPY 267
#define NATIONAL_DEX_DONPHAN 268
#define NATIONAL_DEX_STANTLER 269
#define NATIONAL_DEX_SMEARGLE 270
#define NATIONAL_DEX_MILTANK 271
#define NATIONAL_DEX_RAIKOU 272
#define NATIONAL_DEX_ENTEI 273
#define NATIONAL_DEX_SUICUNE 274
#define NATIONAL_DEX_LARVITAR 275
#define NATIONAL_DEX_PUPITAR 276
#define NATIONAL_DEX_TYRANITAR 277
#define NATIONAL_DEX_LUGIA 278
#define NATIONAL_DEX_HO_OH 279
#define NATIONAL_DEX_CELEBI 280
#define NATIONAL_DEX_TREECKO 281
#define NATIONAL_DEX_GROVYLE 282
#define NATIONAL_DEX_SCEPTILE 283
#define NATIONAL_DEX_TORCHIC 284
#define NATIONAL_DEX_COMBUSKEN 285
#define NATIONAL_DEX_BLAZIKEN 286
#define NATIONAL_DEX_MUDKIP 287
#define NATIONAL_DEX_MARSHTOMP 288
#define NATIONAL_DEX_SWAMPERT 289
#define NATIONAL_DEX_POOCHYENA 290
#define NATIONAL_DEX_MIGHTYENA 291
#define NATIONAL_DEX_ZIGZAGOON 292
#define NATIONAL_DEX_LINOONE 293
#define NATIONAL_DEX_OBSTAGOON 294
#define NATIONAL_DEX_WURMPLE 295
#define NATIONAL_DEX_SILCOON 296
#define NATIONAL_DEX_BEAUTIFLY 297
#define NATIONAL_DEX_CASCOON 298
#define NATIONAL_DEX_DUSTOX 299
#define NATIONAL_DEX_LOTAD 300
#define NATIONAL_DEX_LOMBRE 301
#define NATIONAL_DEX_LUDICOLO 302
#define NATIONAL_DEX_SEEDOT 303
#define NATIONAL_DEX_NUZLEAF 304
#define NATIONAL_DEX_SHIFTRY 305
#define NATIONAL_DEX_TAILLOW 306
#define NATIONAL_DEX_SWELLOW 307
#define NATIONAL_DEX_WINGULL 308
#define NATIONAL_DEX_PELIPPER 309
#define NATIONAL_DEX_RALTS 310
#define NATIONAL_DEX_KIRLIA 311
#define NATIONAL_DEX_GARDEVOIR 312
#define NATIONAL_DEX_GALLADE 313
#define NATIONAL_DEX_SURSKIT 314
#define NATIONAL_DEX_MASQUERAIN 315
#define NATIONAL_DEX_SHROOMISH 316
#define NATIONAL_DEX_BRELOOM 317
#define NATIONAL_DEX_SLAKOTH 318
#define NATIONAL_DEX_VIGOROTH 319
#define NATIONAL_DEX_SLAKING 320
#define NATIONAL_DEX_NINCADA 321
#define NATIONAL_DEX_NINJASK 322
#define NATIONAL_DEX_SHEDINJA 323
#define NATIONAL_DEX_WHISMUR 324
#define NATIONAL_DEX_LOUDRED 325
#define NATIONAL_DEX_EXPLOUD 326
#define NATIONAL_DEX_MAKUHITA 327
#define NATIONAL_DEX_HARIYAMA 328
#define NATIONAL_DEX_NOSEPASS 329
#define NATIONAL_DEX_PROBOPASS 330
#define NATIONAL_DEX_SKITTY 331
#define NATIONAL_DEX_DELCATTY 332
#define NATIONAL_DEX_SABLEYE 333
#define NATIONAL_DEX_MAWILE 334
#define NATIONAL_DEX_ARON 335
#define NATIONAL_DEX_LAIRON 336
#define NATIONAL_DEX_AGGRON 337
#define NATIONAL_DEX_MEDITITE 338
#define NATIONAL_DEX_MEDICHAM 339
#define NATIONAL_DEX_ELECTRIKE 340
#define NATIONAL_DEX_MANECTRIC 341
#define NATIONAL_DEX_PLUSLE 342
#define NATIONAL_DEX_MINUN 343
#define NATIONAL_DEX_VOLBEAT 344
#define NATIONAL_DEX_ILLUMISE 345
#define NATIONAL_DEX_BUDEW 346
#define NATIONAL_DEX_ROSELIA 347
#define NATIONAL_DEX_ROSERADE 348
#define NATIONAL_DEX_GULPIN 349
#define NATIONAL_DEX_SWALOT 350
#define NATIONAL_DEX_CARVANHA 351
#define NATIONAL_DEX_SHARPEDO 352
#define NATIONAL_DEX_WAILMER 353
#define NATIONAL_DEX_WAILORD 354
#define NATIONAL_DEX_NUMEL 355
#define NATIONAL_DEX_CAMERUPT 356
#define NATIONAL_DEX_TORKOAL 357
#define NATIONAL_DEX_SPOINK 358
#define NATIONAL_DEX_GRUMPIG 359
#define NATIONAL_DEX_SPINDA 360
#define NATIONAL_DEX_TRAPINCH 361
#define NATIONAL_DEX_VIBRAVA 362
#define NATIONAL_DEX_FLYGON 363
#define NATIONAL_DEX_CACNEA 364
#define NATIONAL_DEX_CACTURNE 365
#define NATIONAL_DEX_SWABLU 366
#define NATIONAL_DEX_ALTARIA 367
#define NATIONAL_DEX_ZANGOOSE 368
#define NATIONAL_DEX_SEVIPER 369
#define NATIONAL_DEX_LUNATONE 370
#define NATIONAL_DEX_SOLROCK 371
#define NATIONAL_DEX_BARBOACH 372
#define NATIONAL_DEX_WHISCASH 373
#define NATIONAL_DEX_CORPHISH 374
#define NATIONAL_DEX_CRAWDAUNT 375
#define NATIONAL_DEX_BALTOY 376
#define NATIONAL_DEX_CLAYDOL 377
#define NATIONAL_DEX_LILEEP 378
#define NATIONAL_DEX_CRADILY 379
#define NATIONAL_DEX_ANORITH 380
#define NATIONAL_DEX_ARMALDO 381
#define NATIONAL_DEX_FEEBAS 382
#define NATIONAL_DEX_MILOTIC 383
#define NATIONAL_DEX_CASTFORM 384
#define NATIONAL_DEX_CASTFORM 384
#define NATIONAL_DEX_CASTFORM 384
#define NATIONAL_DEX_CASTFORM 384
#define NATIONAL_DEX_KECLEON 385
#define NATIONAL_DEX_SHUPPET 386
#define NATIONAL_DEX_BANETTE 387
#define NATIONAL_DEX_DUSKULL 388
#define NATIONAL_DEX_DUSCLOPS 389
#define NATIONAL_DEX_DUSKNOIR 390
#define NATIONAL_DEX_TROPIUS 391
#define NATIONAL_DEX_CHINGLING 392
#define NATIONAL_DEX_CHIMECHO 393
#define NATIONAL_DEX_ABSOL 394
#define NATIONAL_DEX_SNORUNT 395
#define NATIONAL_DEX_GLALIE 396
#define NATIONAL_DEX_FROSLASS 397
#define NATIONAL_DEX_SPHEAL 398
#define NATIONAL_DEX_SEALEO 399
#define NATIONAL_DEX_WALREIN 400
#define NATIONAL_DEX_CLAMPERL 401
#define NATIONAL_DEX_HUNTAIL 402
#define NATIONAL_DEX_GOREBYSS 403
#define NATIONAL_DEX_RELICANTH 404
#define NATIONAL_DEX_LUVDISC 405
#define NATIONAL_DEX_BAGON 406
#define NATIONAL_DEX_SHELGON 407
#define NATIONAL_DEX_SALAMENCE 408
#define NATIONAL_DEX_BELDUM 409
#define NATIONAL_DEX_METANG 410
#define NATIONAL_DEX_METAGROSS 411
#define NATIONAL_DEX_REGIROCK 412
#define NATIONAL_DEX_REGICE 413
#define NATIONAL_DEX_REGISTEEL 414
#define NATIONAL_DEX_LATIAS 415
#define NATIONAL_DEX_LATIOS 416
#define NATIONAL_DEX_KYOGRE 417
#define NATIONAL_DEX_GROUDON 418
#define NATIONAL_DEX_RAYQUAZA 419
#define NATIONAL_DEX_JIRACHI 420
#define NATIONAL_DEX_DEOXYS 421
#define NATIONAL_DEX_TURTWIG 422
#define NATIONAL_DEX_GROTLE 423
#define NATIONAL_DEX_TORTERRA 424
#define NATIONAL_DEX_CHIMCHAR 425
#define NATIONAL_DEX_MONFERNO 426
#define NATIONAL_DEX_INFERNAPE 427
#define NATIONAL_DEX_PIPLUP 428
#define NATIONAL_DEX_PRINPLUP 429
#define NATIONAL_DEX_EMPOLEON 430
#define NATIONAL_DEX_STARLY 431
#define NATIONAL_DEX_STARAVIA 432
#define NATIONAL_DEX_STARAPTOR 433
#define NATIONAL_DEX_BIDOOF 434
#define NATIONAL_DEX_BIBAREL 435
#define NATIONAL_DEX_KRICKETOT 436
#define NATIONAL_DEX_KRICKETUNE 437
#define NATIONAL_DEX_SHINX  438
#define NATIONAL_DEX_LUXIO  439
#define NATIONAL_DEX_LUXRAY 440
#define NATIONAL_DEX_CRANIDOS 441
#define NATIONAL_DEX_RAMPARDOS 442
#define NATIONAL_DEX_SHIELDON 443
#define NATIONAL_DEX_BASTIODON 444
#define NATIONAL_DEX_BURMY 445
#define NATIONAL_DEX_WORMADAM 446
#define NATIONAL_DEX_MOTHIM 447
#define NATIONAL_DEX_COMBEE 448
#define NATIONAL_DEX_VESPIQUEN 449
#define NATIONAL_DEX_PACHIRISU 450
#define NATIONAL_DEX_BUIZEL 451
#define NATIONAL_DEX_FLOATZEL 452
#define NATIONAL_DEX_CHERUBI 453
#define NATIONAL_DEX_CHERRIM 454
#define NATIONAL_DEX_SHELLOS 455
#define NATIONAL_DEX_GASTRODON 456
#define NATIONAL_DEX_DRIFLOON 457
#define NATIONAL_DEX_DRIFBLIM 458
#define NATIONAL_DEX_BUNEARY 459
#define NATIONAL_DEX_LOPUNNY 460
#define NATIONAL_DEX_GLAMEOW 461
#define NATIONAL_DEX_PURUGLY 462
#define NATIONAL_DEX_STUNKY 463
#define NATIONAL_DEX_SKUNTANK 464
#define NATIONAL_DEX_BRONZOR 465
#define NATIONAL_DEX_BRONZONG 466
#define NATIONAL_DEX_CHATOT 467
#define NATIONAL_DEX_SPIRITOMB 468
#define NATIONAL_DEX_GIBLE 469
#define NATIONAL_DEX_GABITE 470
#define NATIONAL_DEX_GARCHOMP 471
#define NATIONAL_DEX_RIOLU 472
#define NATIONAL_DEX_LUCARIO 473
#define NATIONAL_DEX_HIPPOPOTAS 474
#define NATIONAL_DEX_HIPPOWDON 475
#define NATIONAL_DEX_SKORUPI 476
#define NATIONAL_DEX_DRAPION 477
#define NATIONAL_DEX_CROAGUNK 478
#define NATIONAL_DEX_TOXICROAK 479
#define NATIONAL_DEX_CARNIVINE 480
#define NATIONAL_DEX_FINNEON 481
#define NATIONAL_DEX_LUMINEON 482
#define NATIONAL_DEX_SNOVER 483
#define NATIONAL_DEX_ABOMASNOW 484
#define NATIONAL_DEX_ROTOM 485
#define NATIONAL_DEX_UXIE 486
#define NATIONAL_DEX_MESPRIT 487
#define NATIONAL_DEX_AZELF 488
#define NATIONAL_DEX_DIALGA 489
#define NATIONAL_DEX_PALKIA 490
#define NATIONAL_DEX_HEATRAN 491
#define NATIONAL_DEX_REGIGIGAS 492
#define NATIONAL_DEX_GIRATINA 493
#define NATIONAL_DEX_CRESSELIA 494
#define NATIONAL_DEX_PHIONE 495
#define NATIONAL_DEX_MANAPHY 496
#define NATIONAL_DEX_DARKRAI 497
#define NATIONAL_DEX_SHAYMIN 498
#define NATIONAL_DEX_ARCEUS 499
#define NATIONAL_DEX_VICTINI 500
#define NATIONAL_DEX_SNIVY 501
#define NATIONAL_DEX_SERVINE 502
#define NATIONAL_DEX_SERPERIOR 503
#define NATIONAL_DEX_TEPIG 504
#define NATIONAL_DEX_PIGNITE 505
#define NATIONAL_DEX_EMBOAR 506
#define NATIONAL_DEX_OSHAWOTT 507
#define NATIONAL_DEX_DEWOTT 508
#define NATIONAL_DEX_SAMUROTT 509
#define NATIONAL_DEX_PATRAT 510
#define NATIONAL_DEX_WATCHOG 511
#define NATIONAL_DEX_LILLIPUP 512
#define NATIONAL_DEX_HERDIER 513
#define NATIONAL_DEX_STOUTLAND 514
#define NATIONAL_DEX_PURRLOIN 515
#define NATIONAL_DEX_LIEPARD 516
#define NATIONAL_DEX_PANSAGE 517
#define NATIONAL_DEX_SIMISAGE 518
#define NATIONAL_DEX_PANSEAR 519
#define NATIONAL_DEX_SIMISEAR 520
#define NATIONAL_DEX_PANPOUR 521
#define NATIONAL_DEX_SIMIPOUR 522
#define NATIONAL_DEX_MUNNA 523
#define NATIONAL_DEX_MUSHARNA 524
#define NATIONAL_DEX_PIDOVE 525
#define NATIONAL_DEX_TRANQUILL 526
#define NATIONAL_DEX_UNFEZANT 527
#define NATIONAL_DEX_BLITZLE 528
#define NATIONAL_DEX_ZEBSTRIKA 529
#define NATIONAL_DEX_ROGGENROLA 530
#define NATIONAL_DEX_BOLDORE 531
#define NATIONAL_DEX_GIGALITH 532
#define NATIONAL_DEX_WOOBAT 533
#define NATIONAL_DEX_SWOOBAT 534
#define NATIONAL_DEX_DRILBUR 535
#define NATIONAL_DEX_EXCADRILL 536
#define NATIONAL_DEX_AUDINO 537
#define NATIONAL_DEX_TIMBURR 538
#define NATIONAL_DEX_GURDURR 539
#define NATIONAL_DEX_CONKELDURR 540
#define NATIONAL_DEX_TYMPOLE 541
#define NATIONAL_DEX_PALPITOAD 542
#define NATIONAL_DEX_SEISMITOAD 543
#define NATIONAL_DEX_THROH 544
#define NATIONAL_DEX_SAWK 545
#define NATIONAL_DEX_SEWADDLE 546
#define NATIONAL_DEX_SWADLOON 547
#define NATIONAL_DEX_LEAVANNY 548
#define NATIONAL_DEX_VENIPEDE 549
#define NATIONAL_DEX_WHIRLIPEDE 550
#define NATIONAL_DEX_SCOLIPEDE 551
#define NATIONAL_DEX_COTTONEE 552
#define NATIONAL_DEX_WHIMSICOTT 553
#define NATIONAL_DEX_PETILIL 554
#define NATIONAL_DEX_LILLIGANT 555
#define NATIONAL_DEX_BASCULIN 556
#define NATIONAL_DEX_SANDILE 557
#define NATIONAL_DEX_KROKOROK 558
#define NATIONAL_DEX_KROOKODILE 559
#define NATIONAL_DEX_DARUMAKA 560
#define NATIONAL_DEX_DARMANITAN 561
#define NATIONAL_DEX_MARACTUS 562
#define NATIONAL_DEX_DWEBBLE 563
#define NATIONAL_DEX_CRUSTLE 564
#define NATIONAL_DEX_SCRAGGY 565
#define NATIONAL_DEX_SCRAFTY 566
#define NATIONAL_DEX_SIGILYPH 567
#define NATIONAL_DEX_YAMASK 568
#define NATIONAL_DEX_COFAGRIGUS 569
#define NATIONAL_DEX_RUNERIGUS 570
#define NATIONAL_DEX_TIRTOUGA 571
#define NATIONAL_DEX_CARRACOSTA 572
#define NATIONAL_DEX_ARCHEN 573
#define NATIONAL_DEX_ARCHEOPS 574
#define NATIONAL_DEX_TRUBBISH 575
#define NATIONAL_DEX_GARBODOR 576
#define NATIONAL_DEX_ZORUA 577
#define NATIONAL_DEX_ZOROARK 578
#define NATIONAL_DEX_MINCCINO 579
#define NATIONAL_DEX_CINCCINO 580
#define NATIONAL_DEX_GOTHITA 581
#define NATIONAL_DEX_GOTHORITA 582
#define NATIONAL_DEX_GOTHITELLE 583
#define NATIONAL_DEX_SOLOSIS 584
#define NATIONAL_DEX_DUOSION 585
#define NATIONAL_DEX_REUNICLUS 586
#define NATIONAL_DEX_DUCKLETT 587
#define NATIONAL_DEX_SWANNA 588
#define NATIONAL_DEX_VANILLITE 589
#define NATIONAL_DEX_VANILLISH 590
#define NATIONAL_DEX_VANILLUXE 591
#define NATIONAL_DEX_DEERLING 592
#define NATIONAL_DEX_SAWSBUCK 593
#define NATIONAL_DEX_EMOLGA 594
#define NATIONAL_DEX_KARRABLAST 595
#define NATIONAL_DEX_ESCAVALIER 596
#define NATIONAL_DEX_FOONGUS 597
#define NATIONAL_DEX_AMOONGUSS 598
#define NATIONAL_DEX_FRILLISH 599
#define NATIONAL_DEX_JELLICENT 600
#define NATIONAL_DEX_ALOMOMOLA 601
#define NATIONAL_DEX_JOLTIK 602
#define NATIONAL_DEX_GALVANTULA 603
#define NATIONAL_DEX_FERROSEED 604
#define NATIONAL_DEX_FERROTHORN 605
#define NATIONAL_DEX_KLINK 606
#define NATIONAL_DEX_KLANG 607
#define NATIONAL_DEX_KLINKLANG 608
#define NATIONAL_DEX_TYNAMO 609
#define NATIONAL_DEX_EELEKTRIK 610
#define NATIONAL_DEX_EELEKTROSS 611
#define NATIONAL_DEX_ELGYEM 612
#define NATIONAL_DEX_BEHEEYEM 613
#define NATIONAL_DEX_LITWICK 614
#define NATIONAL_DEX_LAMPENT 615
#define NATIONAL_DEX_CHANDELURE 616
#define NATIONAL_DEX_AXEW 617
#define NATIONAL_DEX_FRAXURE 618
#define NATIONAL_DEX_HAXORUS 619
#define NATIONAL_DEX_CUBCHOO 620
#define NATIONAL_DEX_BEARTIC 621
#define NATIONAL_DEX_CRYOGONAL 622
#define NATIONAL_DEX_SHELMET 623
#define NATIONAL_DEX_ACCELGOR 624
#define NATIONAL_DEX_STUNFISK 625
#define NATIONAL_DEX_MIENFOO 626
#define NATIONAL_DEX_MIENSHAO 627
#define NATIONAL_DEX_DRUDDIGON 628
#define NATIONAL_DEX_GOLETT 629
#define NATIONAL_DEX_GOLURK 630
#define NATIONAL_DEX_PAWNIARD 631
#define NATIONAL_DEX_BISHARP 632
#define NATIONAL_DEX_BOUFFALANT 633
#define NATIONAL_DEX_RUFFLET 634
#define NATIONAL_DEX_BRAVIARY 635
#define NATIONAL_DEX_VULLABY 636
#define NATIONAL_DEX_MANDIBUZZ 637
#define NATIONAL_DEX_HEATMOR 638
#define NATIONAL_DEX_DURANT 639
#define NATIONAL_DEX_DEINO 640
#define NATIONAL_DEX_ZWEILOUS 641
#define NATIONAL_DEX_HYDREIGON 642
#define NATIONAL_DEX_LARVESTA 643
#define NATIONAL_DEX_VOLCARONA 644
#define NATIONAL_DEX_COBALION 645
#define NATIONAL_DEX_TERRAKION 646
#define NATIONAL_DEX_VIRIZION 647
#define NATIONAL_DEX_TORNADUS 648
#define NATIONAL_DEX_THUNDURUS 649
#define NATIONAL_DEX_RESHIRAM 650
#define NATIONAL_DEX_ZEKROM 651
#define NATIONAL_DEX_LANDORUS 652
#define NATIONAL_DEX_KYUREM 653
#define NATIONAL_DEX_KELDEO 654
#define NATIONAL_DEX_MELOETTA 655
#define NATIONAL_DEX_GENESECT 656
#define NATIONAL_DEX_CHESPIN 657
#define NATIONAL_DEX_QUILLADIN 658
#define NATIONAL_DEX_CHESNAUGHT 659
#define NATIONAL_DEX_FENNEKIN 660
#define NATIONAL_DEX_BRAIXEN 661
#define NATIONAL_DEX_DELPHOX 662
#define NATIONAL_DEX_FROAKIE 663
#define NATIONAL_DEX_FROGADIER 664
#define NATIONAL_DEX_GRENINJA 665
#define NATIONAL_DEX_BUNNELBY 666
#define NATIONAL_DEX_DIGGERSBY 667
#define NATIONAL_DEX_FLETCHLING 668
#define NATIONAL_DEX_FLETCHINDER 669
#define NATIONAL_DEX_TALONFLAME 670
#define NATIONAL_DEX_SCATTERBUG 671
#define NATIONAL_DEX_SPEWPA 672
#define NATIONAL_DEX_VIVILLON 673
#define NATIONAL_DEX_LITLEO 674
#define NATIONAL_DEX_PYROAR 675
#define NATIONAL_DEX_FLABEBE 676
#define NATIONAL_DEX_FLOETTE 677
#define NATIONAL_DEX_FLORGES 678
#define NATIONAL_DEX_SKIDDO 679
#define NATIONAL_DEX_GOGOAT 680
#define NATIONAL_DEX_PANCHAM 681
#define NATIONAL_DEX_PANGORO 682
#define NATIONAL_DEX_FURFROU 683
#define NATIONAL_DEX_ESPURR 684
#define NATIONAL_DEX_MEOWSTIC 685
#define NATIONAL_DEX_HONEDGE 686
#define NATIONAL_DEX_DOUBLADE 687
#define NATIONAL_DEX_AEGISLASH 688
#define NATIONAL_DEX_SPRITZEE 689
#define NATIONAL_DEX_AROMATISSE 690
#define NATIONAL_DEX_SWIRLIX 691
#define NATIONAL_DEX_SLURPUFF 692
#define NATIONAL_DEX_INKAY 693
#define NATIONAL_DEX_MALAMAR 694
#define NATIONAL_DEX_BINACLE 695
#define NATIONAL_DEX_BARBARACLE 696
#define NATIONAL_DEX_SKRELP 697
#define NATIONAL_DEX_DRAGALGE 698
#define NATIONAL_DEX_CLAUNCHER 699
#define NATIONAL_DEX_CLAWITZER 700
#define NATIONAL_DEX_HELIOPTILE 701
#define NATIONAL_DEX_HELIOLISK 702
#define NATIONAL_DEX_TYRUNT 703
#define NATIONAL_DEX_TYRANTRUM 704
#define NATIONAL_DEX_AMAURA 705
#define NATIONAL_DEX_AURORUS 706
#define NATIONAL_DEX_HAWLUCHA 707
#define NATIONAL_DEX_DEDENNE 708
#define NATIONAL_DEX_CARBINK 709
#define NATIONAL_DEX_GOOMY 710
#define NATIONAL_DEX_SLIGGOO 711
#define NATIONAL_DEX_GOODRA 712
#define NATIONAL_DEX_KLEFKI 713
#define NATIONAL_DEX_PHANTUMP 714
#define NATIONAL_DEX_TREVENANT 715
#define NATIONAL_DEX_PUMPKABOO 716
#define NATIONAL_DEX_GOURGEIST 717
#define NATIONAL_DEX_BERGMITE 718
#define NATIONAL_DEX_AVALUGG 719
#define NATIONAL_DEX_NOIBAT 720
#define NATIONAL_DEX_NOIVERN 721
#define NATIONAL_DEX_XERNEAS 722
#define NATIONAL_DEX_YVELTAL 723
#define NATIONAL_DEX_ZYGARDE 724
#define NATIONAL_DEX_DIANCIE 725
#define NATIONAL_DEX_HOOPA 726
#define NATIONAL_DEX_VOLCANION 727
#define NATIONAL_DEX_ROWLET 728
#define NATIONAL_DEX_DARTRIX 729
#define NATIONAL_DEX_DECIDUEYE 730
#define NATIONAL_DEX_LITTEN 731
#define NATIONAL_DEX_TORRACAT 732
#define NATIONAL_DEX_INCINEROAR 733
#define NATIONAL_DEX_POPPLIO 734
#define NATIONAL_DEX_BRIONNE 735
#define NATIONAL_DEX_PRIMARINA 736
#define NATIONAL_DEX_PIKIPEK 737
#define NATIONAL_DEX_TRUMBEAK 738
#define NATIONAL_DEX_TOUCANNON 739
#define NATIONAL_DEX_YUNGOOS 740
#define NATIONAL_DEX_GUMSHOOS 741
#define NATIONAL_DEX_GRUBBIN 742
#define NATIONAL_DEX_CHARJABUG 743
#define NATIONAL_DEX_VIKAVOLT 744
#define NATIONAL_DEX_CRABRAWLER 745
#define NATIONAL_DEX_CRABOMINABLE 746
#define NATIONAL_DEX_ORICORIO 747
#define NATIONAL_DEX_CUTIEFLY 748
#define NATIONAL_DEX_RIBOMBEE 749
#define NATIONAL_DEX_ROCKRUFF 750
#define NATIONAL_DEX_LYCANROC 751
#define NATIONAL_DEX_WISHIWASHI 752
#define NATIONAL_DEX_MAREANIE 753
#define NATIONAL_DEX_TOXAPEX 754
#define NATIONAL_DEX_MUDBRAY 755
#define NATIONAL_DEX_MUDSDALE 756
#define NATIONAL_DEX_DEWPIDER 757
#define NATIONAL_DEX_ARAQUANID 758
#define NATIONAL_DEX_FOMANTIS 759
#define NATIONAL_DEX_LURANTIS 760
#define NATIONAL_DEX_MORELULL 761
#define NATIONAL_DEX_SHIINOTIC 762
#define NATIONAL_DEX_SALANDIT 763
#define NATIONAL_DEX_SALAZZLE 764
#define NATIONAL_DEX_STUFFUL 765
#define NATIONAL_DEX_BEWEAR 766
#define NATIONAL_DEX_BOUNSWEET 767
#define NATIONAL_DEX_STEENEE 768
#define NATIONAL_DEX_TSAREENA 769
#define NATIONAL_DEX_COMFEY 770
#define NATIONAL_DEX_ORANGURU 771
#define NATIONAL_DEX_PASSIMIAN 772
#define NATIONAL_DEX_WIMPOD 773
#define NATIONAL_DEX_GOLISOPOD 774
#define NATIONAL_DEX_SANDYGAST 775
#define NATIONAL_DEX_PALOSSAND 776
#define NATIONAL_DEX_PYUKUMUKU 777
#define NATIONAL_DEX_TYPE_NULL 778
#define NATIONAL_DEX_SILVALLY 779
#define NATIONAL_DEX_MINIOR 780
#define NATIONAL_DEX_KOMALA 781
#define NATIONAL_DEX_TURTONATOR 782
#define NATIONAL_DEX_TOGEDEMARU 783
#define NATIONAL_DEX_MIMIKYU 784
#define NATIONAL_DEX_BRUXISH 785
#define NATIONAL_DEX_DRAMPA 786
#define NATIONAL_DEX_DHELMISE 787
#define NATIONAL_DEX_JANGMO_O 788
#define NATIONAL_DEX_HAKAMO_O 789
#define NATIONAL_DEX_KOMMO_O 790
#define NATIONAL_DEX_TAPU_KOKO 791
#define NATIONAL_DEX_TAPU_LELE 792
#define NATIONAL_DEX_TAPU_BULU 793
#define NATIONAL_DEX_TAPU_FINI 794
#define NATIONAL_DEX_COSMOG 795
#define NATIONAL_DEX_COSMOEM 796
#define NATIONAL_DEX_SOLGALEO 797
#define NATIONAL_DEX_LUNALA 798
#define NATIONAL_DEX_NIHILEGO 799
#define NATIONAL_DEX_BUZZWOLE 800
#define NATIONAL_DEX_PHEROMOSA 801
#define NATIONAL_DEX_XURKITREE 802
#define NATIONAL_DEX_CELESTEELA 803
#define NATIONAL_DEX_KARTANA 804
#define NATIONAL_DEX_GUZZLORD 805
#define NATIONAL_DEX_NECROZMA 806
#define NATIONAL_DEX_MAGEARNA 807
#define NATIONAL_DEX_MARSHADOW 808
#define NATIONAL_DEX_POIPOLE 809
#define NATIONAL_DEX_NAGANADEL 810
#define NATIONAL_DEX_STAKATAKA 811
#define NATIONAL_DEX_BLACEPHALON 812
#define NATIONAL_DEX_ZERAORA 813
#define NATIONAL_DEX_MELTAN 814
#define NATIONAL_DEX_MELMETAL 815
#define NATIONAL_DEX_GROOKEY 816
#define NATIONAL_DEX_THWACKEY 817
#define NATIONAL_DEX_RILLABOOM 818
#define NATIONAL_DEX_SCORBUNNY 819
#define NATIONAL_DEX_RABOOT 820
#define NATIONAL_DEX_CINDERACE 821
#define NATIONAL_DEX_SOBBLE 822
#define NATIONAL_DEX_DRIZZILE 823
#define NATIONAL_DEX_INTELEON 824
#define NATIONAL_DEX_SKWOVET 825
#define NATIONAL_DEX_GREEDENT 826
#define NATIONAL_DEX_ROOKIDEE 827
#define NATIONAL_DEX_CORVISQUIRE 828
#define NATIONAL_DEX_CORVIKNIGHT 829
#define NATIONAL_DEX_BLIPBUG 830
#define NATIONAL_DEX_DOTTLER 831
#define NATIONAL_DEX_ORBEETLE 832
#define NATIONAL_DEX_NICKIT 833
#define NATIONAL_DEX_THIEVUL 834
#define NATIONAL_DEX_GOSSIFLEUR 835
#define NATIONAL_DEX_ELDEGOSS 836
#define NATIONAL_DEX_WOOLOO 837
#define NATIONAL_DEX_DUBWOOL 838
#define NATIONAL_DEX_CHEWTLE 839
#define NATIONAL_DEX_DREDNAW 840
#define NATIONAL_DEX_YAMPER 841
#define NATIONAL_DEX_BOLTUND 842
#define NATIONAL_DEX_ROLYCOLY 843
#define NATIONAL_DEX_CARKOL 844
#define NATIONAL_DEX_COALOSSAL 845
#define NATIONAL_DEX_APPLIN 846
#define NATIONAL_DEX_FLAPPLE 847
#define NATIONAL_DEX_APPLETUN 848
#define NATIONAL_DEX_SILICOBRA 849
#define NATIONAL_DEX_SANDACONDA 850
#define NATIONAL_DEX_CRAMORANT 851
#define NATIONAL_DEX_ARROKUDA 852
#define NATIONAL_DEX_BARRASKEWDA 853
#define NATIONAL_DEX_TOXEL 854
#define NATIONAL_DEX_TOXTRICITY 855
#define NATIONAL_DEX_SIZZLIPEDE 856
#define NATIONAL_DEX_CENTISKORCH 857
#define NATIONAL_DEX_CLOBBOPUS 858
#define NATIONAL_DEX_GRAPPLOCT 859
#define NATIONAL_DEX_SINISTEA 860
#define NATIONAL_DEX_POLTEAGEIST 861
#define NATIONAL_DEX_HATENNA 862
#define NATIONAL_DEX_HATTREM 863
#define NATIONAL_DEX_HATTERENE 864
#define NATIONAL_DEX_IMPIDIMP 865
#define NATIONAL_DEX_MORGREM 866
#define NATIONAL_DEX_GRIMMSNARL 867
#define NATIONAL_DEX_MILCERY 868
#define NATIONAL_DEX_ALCREMIE 869
#define NATIONAL_DEX_FALINKS 870
#define NATIONAL_DEX_PINCURCHIN 871
#define NATIONAL_DEX_SNOM 872
#define NATIONAL_DEX_FROSMOTH 873
#define NATIONAL_DEX_STONJOURNER 874
#define NATIONAL_DEX_EISCUE 875
#define NATIONAL_DEX_INDEEDEE 876
#define NATIONAL_DEX_MORPEKO 877
#define NATIONAL_DEX_CUFANT 878
#define NATIONAL_DEX_COPPERAJAH 879
#define NATIONAL_DEX_DRACOZOLT 880
#define NATIONAL_DEX_ARCTOZOLT 881
#define NATIONAL_DEX_DRACOVISH 882
#define NATIONAL_DEX_ARCTOVISH 883
#define NATIONAL_DEX_DURALUDON 884
#define NATIONAL_DEX_DREEPY 885
#define NATIONAL_DEX_DRAKLOAK 886
#define NATIONAL_DEX_DRAGAPULT 887
#define NATIONAL_DEX_ZACIAN 888
#define NATIONAL_DEX_ZAMAZENTA 889
#define NATIONAL_DEX_ETERNATUS 890
#define NATIONAL_DEX_KUBFU 891
#define NATIONAL_DEX_URSHIFU 892
#define NATIONAL_DEX_ZARUDE 893
#define NATIONAL_DEX_REGIELEKI 894
#define NATIONAL_DEX_REGIDRAGO 895
#define NATIONAL_DEX_GLASTRIER 896
#define NATIONAL_DEX_SPECTRIER 897
#define NATIONAL_DEX_CALYREX 898

#define FINAL_DEX_ENTRY NATIONAL_DEX_CALYREX //Not +1 b/c used like this for some asm
#define NATIONAL_DEX_COUNT FINAL_DEX_ENTRY + 1

extern const u8 DEX_ENTRY_TURTWIG[];
extern const u8 DEX_ENTRY_GROTLE[];
extern const u8 DEX_ENTRY_TORTERRA[];
extern const u8 DEX_ENTRY_CHIMCHAR[];
extern const u8 DEX_ENTRY_MONFERNO[];
extern const u8 DEX_ENTRY_INFERNAPE[];
extern const u8 DEX_ENTRY_PIPLUP[];
extern const u8 DEX_ENTRY_PRINPLUP[];
extern const u8 DEX_ENTRY_EMPOLEON[];
extern const u8 DEX_ENTRY_STARLY[];
extern const u8 DEX_ENTRY_STARAVIA[];
extern const u8 DEX_ENTRY_STARAPTOR[];
extern const u8 DEX_ENTRY_BIDOOF[];
extern const u8 DEX_ENTRY_BIBAREL[];
extern const u8 DEX_ENTRY_KRICKETOT[];
extern const u8 DEX_ENTRY_KRICKETUNE[];
extern const u8 DEX_ENTRY_SHINX[];
extern const u8 DEX_ENTRY_LUXIO[];
extern const u8 DEX_ENTRY_LUXRAY[];
extern const u8 DEX_ENTRY_BUDEW[];
extern const u8 DEX_ENTRY_ROSERADE[];
extern const u8 DEX_ENTRY_CRANIDOS[];
extern const u8 DEX_ENTRY_RAMPARDOS[];
extern const u8 DEX_ENTRY_SHIELDON[];
extern const u8 DEX_ENTRY_BASTIODON[];
extern const u8 DEX_ENTRY_BURMY[];
extern const u8 DEX_ENTRY_WORMADAM[];
extern const u8 DEX_ENTRY_MOTHIM[];
extern const u8 DEX_ENTRY_COMBEE[];
extern const u8 DEX_ENTRY_VESPIQUEN[];
extern const u8 DEX_ENTRY_PACHIRISU[];
extern const u8 DEX_ENTRY_BUIZEL[];
extern const u8 DEX_ENTRY_FLOATZEL[];
extern const u8 DEX_ENTRY_CHERUBI[];
extern const u8 DEX_ENTRY_CHERRIM[];
extern const u8 DEX_ENTRY_SHELLOS[];
extern const u8 DEX_ENTRY_GASTRODON[];
extern const u8 DEX_ENTRY_AMBIPOM[];
extern const u8 DEX_ENTRY_DRIFLOON[];
extern const u8 DEX_ENTRY_DRIFBLIM[];
extern const u8 DEX_ENTRY_BUNEARY[];
extern const u8 DEX_ENTRY_LOPUNNY[];
extern const u8 DEX_ENTRY_MISMAGIUS[];
extern const u8 DEX_ENTRY_HONCHKROW[];
extern const u8 DEX_ENTRY_GLAMEOW[];
extern const u8 DEX_ENTRY_PURUGLY[];
extern const u8 DEX_ENTRY_CHINGLING[];
extern const u8 DEX_ENTRY_STUNKY[];
extern const u8 DEX_ENTRY_SKUNTANK[];
extern const u8 DEX_ENTRY_BRONZOR[];
extern const u8 DEX_ENTRY_BRONZONG[];
extern const u8 DEX_ENTRY_BONSLY[];
extern const u8 DEX_ENTRY_MIME_JR[];
extern const u8 DEX_ENTRY_HAPPINY[];
extern const u8 DEX_ENTRY_CHATOT[];
extern const u8 DEX_ENTRY_SPIRITOMB[];
extern const u8 DEX_ENTRY_GIBLE[];
extern const u8 DEX_ENTRY_GABITE[];
extern const u8 DEX_ENTRY_GARCHOMP[];
extern const u8 DEX_ENTRY_MUNCHLAX[];
extern const u8 DEX_ENTRY_RIOLU[];
extern const u8 DEX_ENTRY_LUCARIO[];
extern const u8 DEX_ENTRY_HIPPOPOTAS[];
extern const u8 DEX_ENTRY_HIPPOWDON[];
extern const u8 DEX_ENTRY_SKORUPI[];
extern const u8 DEX_ENTRY_DRAPION[];
extern const u8 DEX_ENTRY_CROAGUNK[];
extern const u8 DEX_ENTRY_TOXICROAK[];
extern const u8 DEX_ENTRY_CARNIVINE[];
extern const u8 DEX_ENTRY_FINNEON[];
extern const u8 DEX_ENTRY_LUMINEON[];
extern const u8 DEX_ENTRY_MANTYKE[];
extern const u8 DEX_ENTRY_SNOVER[];
extern const u8 DEX_ENTRY_ABOMASNOW[];
extern const u8 DEX_ENTRY_WEAVILE[];
extern const u8 DEX_ENTRY_MAGNEZONE[];
extern const u8 DEX_ENTRY_LICKILICKY[];
extern const u8 DEX_ENTRY_RHYPERIOR[];
extern const u8 DEX_ENTRY_TANGROWTH[];
extern const u8 DEX_ENTRY_ELECTIVIRE[];
extern const u8 DEX_ENTRY_MAGMORTAR[];
extern const u8 DEX_ENTRY_TOGEKISS[];
extern const u8 DEX_ENTRY_YANMEGA[];
extern const u8 DEX_ENTRY_LEAFEON[];
extern const u8 DEX_ENTRY_GLACEON[];
extern const u8 DEX_ENTRY_GLISCOR[];
extern const u8 DEX_ENTRY_MAMOSWINE[];
extern const u8 DEX_ENTRY_PORYGON_Z[];
extern const u8 DEX_ENTRY_GALLADE[];
extern const u8 DEX_ENTRY_PROBOPASS[];
extern const u8 DEX_ENTRY_DUSKNOIR[];
extern const u8 DEX_ENTRY_FROSLASS[];
extern const u8 DEX_ENTRY_ROTOM[];
extern const u8 DEX_ENTRY_UXIE[];
extern const u8 DEX_ENTRY_MESPRIT[];
extern const u8 DEX_ENTRY_AZELF[];
extern const u8 DEX_ENTRY_DIALGA[];
extern const u8 DEX_ENTRY_PALKIA[];
extern const u8 DEX_ENTRY_HEATRAN[];
extern const u8 DEX_ENTRY_REGIGIGAS[];
extern const u8 DEX_ENTRY_GIRATINA[];
extern const u8 DEX_ENTRY_CRESSELIA[];
extern const u8 DEX_ENTRY_PHIONE[];
extern const u8 DEX_ENTRY_MANAPHY[];
extern const u8 DEX_ENTRY_DARKRAI[];
extern const u8 DEX_ENTRY_SHAYMIN[];
extern const u8 DEX_ENTRY_ARCEUS[];
extern const u8 DEX_ENTRY_VICTINI[];
extern const u8 DEX_ENTRY_SNIVY[];
extern const u8 DEX_ENTRY_SERVINE[];
extern const u8 DEX_ENTRY_SERPERIOR[];
extern const u8 DEX_ENTRY_TEPIG[];
extern const u8 DEX_ENTRY_PIGNITE[];
extern const u8 DEX_ENTRY_EMBOAR[];
extern const u8 DEX_ENTRY_OSHAWOTT[];
extern const u8 DEX_ENTRY_DEWOTT[];
extern const u8 DEX_ENTRY_SAMUROTT[];
extern const u8 DEX_ENTRY_PATRAT[];
extern const u8 DEX_ENTRY_WATCHOG[];
extern const u8 DEX_ENTRY_LILLIPUP[];
extern const u8 DEX_ENTRY_HERDIER[];
extern const u8 DEX_ENTRY_STOUTLAND[];
extern const u8 DEX_ENTRY_PURRLOIN[];
extern const u8 DEX_ENTRY_LIEPARD[];
extern const u8 DEX_ENTRY_PANSAGE[];
extern const u8 DEX_ENTRY_SIMISAGE[];
extern const u8 DEX_ENTRY_PANSEAR[];
extern const u8 DEX_ENTRY_SIMISEAR[];
extern const u8 DEX_ENTRY_PANPOUR[];
extern const u8 DEX_ENTRY_SIMIPOUR[];
extern const u8 DEX_ENTRY_MUNNA[];
extern const u8 DEX_ENTRY_MUSHARNA[];
extern const u8 DEX_ENTRY_PIDOVE[];
extern const u8 DEX_ENTRY_TRANQUILL[];
extern const u8 DEX_ENTRY_UNFEZANT[];
extern const u8 DEX_ENTRY_BLITZLE[];
extern const u8 DEX_ENTRY_ZEBSTRIKA[];
extern const u8 DEX_ENTRY_ROGGENROLA[];
extern const u8 DEX_ENTRY_BOLDORE[];
extern const u8 DEX_ENTRY_GIGALITH[];
extern const u8 DEX_ENTRY_WOOBAT[];
extern const u8 DEX_ENTRY_SWOOBAT[];
extern const u8 DEX_ENTRY_DRILBUR[];
extern const u8 DEX_ENTRY_EXCADRILL[];
extern const u8 DEX_ENTRY_AUDINO[];
extern const u8 DEX_ENTRY_TIMBURR[];
extern const u8 DEX_ENTRY_GURDURR[];
extern const u8 DEX_ENTRY_CONKELDURR[];
extern const u8 DEX_ENTRY_TYMPOLE[];
extern const u8 DEX_ENTRY_PALPITOAD[];
extern const u8 DEX_ENTRY_SEISMITOAD[];
extern const u8 DEX_ENTRY_THROH[];
extern const u8 DEX_ENTRY_SAWK[];
extern const u8 DEX_ENTRY_SEWADDLE[];
extern const u8 DEX_ENTRY_SWADLOON[];
extern const u8 DEX_ENTRY_LEAVANNY[];
extern const u8 DEX_ENTRY_VENIPEDE[];
extern const u8 DEX_ENTRY_WHIRLIPEDE[];
extern const u8 DEX_ENTRY_SCOLIPEDE[];
extern const u8 DEX_ENTRY_COTTONEE[];
extern const u8 DEX_ENTRY_WHIMSICOTT[];
extern const u8 DEX_ENTRY_PETILIL[];
extern const u8 DEX_ENTRY_LILLIGANT[];
extern const u8 DEX_ENTRY_BASCULIN[];
extern const u8 DEX_ENTRY_SANDILE[];
extern const u8 DEX_ENTRY_KROKOROK[];
extern const u8 DEX_ENTRY_KROOKODILE[];
extern const u8 DEX_ENTRY_DARUMAKA[];
extern const u8 DEX_ENTRY_DARMANITAN[];
extern const u8 DEX_ENTRY_MARACTUS[];
extern const u8 DEX_ENTRY_DWEBBLE[];
extern const u8 DEX_ENTRY_CRUSTLE[];
extern const u8 DEX_ENTRY_SCRAGGY[];
extern const u8 DEX_ENTRY_SCRAFTY[];
extern const u8 DEX_ENTRY_SIGILYPH[];
extern const u8 DEX_ENTRY_YAMASK[];
extern const u8 DEX_ENTRY_COFAGRIGUS[];
extern const u8 DEX_ENTRY_TIRTOUGA[];
extern const u8 DEX_ENTRY_CARRACOSTA[];
extern const u8 DEX_ENTRY_ARCHEN[];
extern const u8 DEX_ENTRY_ARCHEOPS[];
extern const u8 DEX_ENTRY_TRUBBISH[];
extern const u8 DEX_ENTRY_GARBODOR[];
extern const u8 DEX_ENTRY_ZORUA[];
extern const u8 DEX_ENTRY_ZOROARK[];
extern const u8 DEX_ENTRY_MINCCINO[];
extern const u8 DEX_ENTRY_CINCCINO[];
extern const u8 DEX_ENTRY_GOTHITA[];
extern const u8 DEX_ENTRY_GOTHORITA[];
extern const u8 DEX_ENTRY_GOTHITELLE[];
extern const u8 DEX_ENTRY_SOLOSIS[];
extern const u8 DEX_ENTRY_DUOSION[];
extern const u8 DEX_ENTRY_REUNICLUS[];
extern const u8 DEX_ENTRY_DUCKLETT[];
extern const u8 DEX_ENTRY_SWANNA[];
extern const u8 DEX_ENTRY_VANILLITE[];
extern const u8 DEX_ENTRY_VANILLISH[];
extern const u8 DEX_ENTRY_VANILLUXE[];
extern const u8 DEX_ENTRY_DEERLING[];
extern const u8 DEX_ENTRY_SAWSBUCK[];
extern const u8 DEX_ENTRY_EMOLGA[];
extern const u8 DEX_ENTRY_KARRABLAST[];
extern const u8 DEX_ENTRY_ESCAVALIER[];
extern const u8 DEX_ENTRY_FOONGUS[];
extern const u8 DEX_ENTRY_AMOONGUSS[];
extern const u8 DEX_ENTRY_FRILLISH[];
extern const u8 DEX_ENTRY_JELLICENT[];
extern const u8 DEX_ENTRY_ALOMOMOLA[];
extern const u8 DEX_ENTRY_JOLTIK[];
extern const u8 DEX_ENTRY_GALVANTULA[];
extern const u8 DEX_ENTRY_FERROSEED[];
extern const u8 DEX_ENTRY_FERROTHORN[];
extern const u8 DEX_ENTRY_KLINK[];
extern const u8 DEX_ENTRY_KLANG[];
extern const u8 DEX_ENTRY_KLINKLANG[];
extern const u8 DEX_ENTRY_TYNAMO[];
extern const u8 DEX_ENTRY_EELEKTRIK[];
extern const u8 DEX_ENTRY_EELEKTROSS[];
extern const u8 DEX_ENTRY_ELGYEM[];
extern const u8 DEX_ENTRY_BEHEEYEM[];
extern const u8 DEX_ENTRY_LITWICK[];
extern const u8 DEX_ENTRY_LAMPENT[];
extern const u8 DEX_ENTRY_CHANDELURE[];
extern const u8 DEX_ENTRY_AXEW[];
extern const u8 DEX_ENTRY_FRAXURE[];
extern const u8 DEX_ENTRY_HAXORUS[];
extern const u8 DEX_ENTRY_CUBCHOO[];
extern const u8 DEX_ENTRY_BEARTIC[];
extern const u8 DEX_ENTRY_CRYOGONAL[];
extern const u8 DEX_ENTRY_SHELMET[];
extern const u8 DEX_ENTRY_ACCELGOR[];
extern const u8 DEX_ENTRY_STUNFISK[];
extern const u8 DEX_ENTRY_MIENFOO[];
extern const u8 DEX_ENTRY_MIENSHAO[];
extern const u8 DEX_ENTRY_DRUDDIGON[];
extern const u8 DEX_ENTRY_GOLETT[];
extern const u8 DEX_ENTRY_GOLURK[];
extern const u8 DEX_ENTRY_PAWNIARD[];
extern const u8 DEX_ENTRY_BISHARP[];
extern const u8 DEX_ENTRY_BOUFFALANT[];
extern const u8 DEX_ENTRY_RUFFLET[];
extern const u8 DEX_ENTRY_BRAVIARY[];
extern const u8 DEX_ENTRY_VULLABY[];
extern const u8 DEX_ENTRY_MANDIBUZZ[];
extern const u8 DEX_ENTRY_HEATMOR[];
extern const u8 DEX_ENTRY_DURANT[];
extern const u8 DEX_ENTRY_DEINO[];
extern const u8 DEX_ENTRY_ZWEILOUS[];
extern const u8 DEX_ENTRY_HYDREIGON[];
extern const u8 DEX_ENTRY_LARVESTA[];
extern const u8 DEX_ENTRY_VOLCARONA[];
extern const u8 DEX_ENTRY_COBALION[];
extern const u8 DEX_ENTRY_TERRAKION[];
extern const u8 DEX_ENTRY_VIRIZION[];
extern const u8 DEX_ENTRY_TORNADUS[];
extern const u8 DEX_ENTRY_THUNDURUS[];
extern const u8 DEX_ENTRY_RESHIRAM[];
extern const u8 DEX_ENTRY_ZEKROM[];
extern const u8 DEX_ENTRY_LANDORUS[];
extern const u8 DEX_ENTRY_KYUREM[];
extern const u8 DEX_ENTRY_KELDEO[];
extern const u8 DEX_ENTRY_MELOETTA[];
extern const u8 DEX_ENTRY_GENESECT[];
extern const u8 DEX_ENTRY_CHESPIN[];
extern const u8 DEX_ENTRY_QUILLADIN[];
extern const u8 DEX_ENTRY_CHESNAUGHT[];
extern const u8 DEX_ENTRY_FENNEKIN[];
extern const u8 DEX_ENTRY_BRAIXEN[];
extern const u8 DEX_ENTRY_DELPHOX[];
extern const u8 DEX_ENTRY_FROAKIE[];
extern const u8 DEX_ENTRY_FROGADIER[];
extern const u8 DEX_ENTRY_GRENINJA[];
extern const u8 DEX_ENTRY_BUNNELBY[];
extern const u8 DEX_ENTRY_DIGGERSBY[];
extern const u8 DEX_ENTRY_FLETCHLING[];
extern const u8 DEX_ENTRY_FLETCHINDER[];
extern const u8 DEX_ENTRY_TALONFLAME[];
extern const u8 DEX_ENTRY_SCATTERBUG[];
extern const u8 DEX_ENTRY_SPEWPA[];
extern const u8 DEX_ENTRY_VIVILLON[];
extern const u8 DEX_ENTRY_LITLEO[];
extern const u8 DEX_ENTRY_PYROAR[];
extern const u8 DEX_ENTRY_FLABEBE[];
extern const u8 DEX_ENTRY_FLOETTE[];
extern const u8 DEX_ENTRY_FLORGES[];
extern const u8 DEX_ENTRY_SKIDDO[];
extern const u8 DEX_ENTRY_GOGOAT[];
extern const u8 DEX_ENTRY_PANCHAM[];
extern const u8 DEX_ENTRY_PANGORO[];
extern const u8 DEX_ENTRY_FURFROU[];
extern const u8 DEX_ENTRY_ESPURR[];
extern const u8 DEX_ENTRY_MEOWSTIC[];
extern const u8 DEX_ENTRY_HONEDGE[];
extern const u8 DEX_ENTRY_DOUBLADE[];
extern const u8 DEX_ENTRY_AEGISLASH[];
extern const u8 DEX_ENTRY_SPRITZEE[];
extern const u8 DEX_ENTRY_AROMATISSE[];
extern const u8 DEX_ENTRY_SWIRLIX[];
extern const u8 DEX_ENTRY_SLURPUFF[];
extern const u8 DEX_ENTRY_INKAY[];
extern const u8 DEX_ENTRY_MALAMAR[];
extern const u8 DEX_ENTRY_BINACLE[];
extern const u8 DEX_ENTRY_BARBARACLE[];
extern const u8 DEX_ENTRY_SKRELP[];
extern const u8 DEX_ENTRY_DRAGALGE[];
extern const u8 DEX_ENTRY_CLAUNCHER[];
extern const u8 DEX_ENTRY_CLAWITZER[];
extern const u8 DEX_ENTRY_HELIOPTILE[];
extern const u8 DEX_ENTRY_HELIOLISK[];
extern const u8 DEX_ENTRY_TYRUNT[];
extern const u8 DEX_ENTRY_TYRANTRUM[];
extern const u8 DEX_ENTRY_AMAURA[];
extern const u8 DEX_ENTRY_AURORUS[];
extern const u8 DEX_ENTRY_SYLVEON[];
extern const u8 DEX_ENTRY_HAWLUCHA[];
extern const u8 DEX_ENTRY_DEDENNE[];
extern const u8 DEX_ENTRY_CARBINK[];
extern const u8 DEX_ENTRY_GOOMY[];
extern const u8 DEX_ENTRY_SLIGGOO[];
extern const u8 DEX_ENTRY_GOODRA[];
extern const u8 DEX_ENTRY_KLEFKI[];
extern const u8 DEX_ENTRY_PHANTUMP[];
extern const u8 DEX_ENTRY_TREVENANT[];
extern const u8 DEX_ENTRY_PUMPKABOO[];
extern const u8 DEX_ENTRY_GOURGEIST[];
extern const u8 DEX_ENTRY_BERGMITE[];
extern const u8 DEX_ENTRY_AVALUGG[];
extern const u8 DEX_ENTRY_NOIBAT[];
extern const u8 DEX_ENTRY_NOIVERN[];
extern const u8 DEX_ENTRY_XERNEAS[];
extern const u8 DEX_ENTRY_YVELTAL[];
extern const u8 DEX_ENTRY_ZYGARDE[];
extern const u8 DEX_ENTRY_DIANCIE[];
extern const u8 DEX_ENTRY_HOOPA[];
extern const u8 DEX_ENTRY_VOLCANION[];
extern const u8 DEX_ENTRY_ROWLET[];
extern const u8 DEX_ENTRY_DARTRIX[];
extern const u8 DEX_ENTRY_DECIDUEYE[];
extern const u8 DEX_ENTRY_LITTEN[];
extern const u8 DEX_ENTRY_TORRACAT[];
extern const u8 DEX_ENTRY_INCINEROAR[];
extern const u8 DEX_ENTRY_POPPLIO[];
extern const u8 DEX_ENTRY_BRIONNE[];
extern const u8 DEX_ENTRY_PRIMARINA[];
extern const u8 DEX_ENTRY_PIKIPEK[];
extern const u8 DEX_ENTRY_TRUMBEAK[];
extern const u8 DEX_ENTRY_TOUCANNON[];
extern const u8 DEX_ENTRY_YUNGOOS[];
extern const u8 DEX_ENTRY_GUMSHOOS[];
extern const u8 DEX_ENTRY_GRUBBIN[];
extern const u8 DEX_ENTRY_CHARJABUG[];
extern const u8 DEX_ENTRY_VIKAVOLT[];
extern const u8 DEX_ENTRY_CRABRAWLER[];
extern const u8 DEX_ENTRY_CRABOMINABLE[];
extern const u8 DEX_ENTRY_ORICORIO[];
extern const u8 DEX_ENTRY_CUTIEFLY[];
extern const u8 DEX_ENTRY_RIBOMBEE[];
extern const u8 DEX_ENTRY_ROCKRUFF[];
extern const u8 DEX_ENTRY_LYCANROC[];
extern const u8 DEX_ENTRY_WISHIWASHI[];
extern const u8 DEX_ENTRY_MAREANIE[];
extern const u8 DEX_ENTRY_TOXAPEX[];
extern const u8 DEX_ENTRY_MUDBRAY[];
extern const u8 DEX_ENTRY_MUDSDALE[];
extern const u8 DEX_ENTRY_DEWPIDER[];
extern const u8 DEX_ENTRY_ARAQUANID[];
extern const u8 DEX_ENTRY_FOMANTIS[];
extern const u8 DEX_ENTRY_LURANTIS[];
extern const u8 DEX_ENTRY_MORELULL[];
extern const u8 DEX_ENTRY_SHIINOTIC[];
extern const u8 DEX_ENTRY_SALANDIT[];
extern const u8 DEX_ENTRY_SALAZZLE[];
extern const u8 DEX_ENTRY_STUFFUL[];
extern const u8 DEX_ENTRY_BEWEAR[];
extern const u8 DEX_ENTRY_BOUNSWEET[];
extern const u8 DEX_ENTRY_STEENEE[];
extern const u8 DEX_ENTRY_TSAREENA[];
extern const u8 DEX_ENTRY_COMFEY[];
extern const u8 DEX_ENTRY_ORANGURU[];
extern const u8 DEX_ENTRY_PASSIMIAN[];
extern const u8 DEX_ENTRY_WIMPOD[];
extern const u8 DEX_ENTRY_GOLISOPOD[];
extern const u8 DEX_ENTRY_SANDYGAST[];
extern const u8 DEX_ENTRY_PALOSSAND[];
extern const u8 DEX_ENTRY_PYUKUMUKU[];
extern const u8 DEX_ENTRY_TYPE_NULL[];
extern const u8 DEX_ENTRY_SILVALLY[];
extern const u8 DEX_ENTRY_MINIOR[];
extern const u8 DEX_ENTRY_KOMALA[];
extern const u8 DEX_ENTRY_TURTONATOR[];
extern const u8 DEX_ENTRY_TOGEDEMARU[];
extern const u8 DEX_ENTRY_MIMIKYU[];
extern const u8 DEX_ENTRY_BRUXISH[];
extern const u8 DEX_ENTRY_DRAMPA[];
extern const u8 DEX_ENTRY_DHELMISE[];
extern const u8 DEX_ENTRY_JANGMO_O[];
extern const u8 DEX_ENTRY_HAKAMO_O[];
extern const u8 DEX_ENTRY_KOMMO_O[];
extern const u8 DEX_ENTRY_TAPU_KOKO[];
extern const u8 DEX_ENTRY_TAPU_LELE[];
extern const u8 DEX_ENTRY_TAPU_BULU[];
extern const u8 DEX_ENTRY_TAPU_FINI[];
extern const u8 DEX_ENTRY_COSMOG[];
extern const u8 DEX_ENTRY_COSMOEM[];
extern const u8 DEX_ENTRY_SOLGALEO[];
extern const u8 DEX_ENTRY_LUNALA[];
extern const u8 DEX_ENTRY_NIHILEGO[];
extern const u8 DEX_ENTRY_BUZZWOLE[];
extern const u8 DEX_ENTRY_PHEROMOSA[];
extern const u8 DEX_ENTRY_XURKITREE[];
extern const u8 DEX_ENTRY_CELESTEELA[];
extern const u8 DEX_ENTRY_KARTANA[];
extern const u8 DEX_ENTRY_GUZZLORD[];
extern const u8 DEX_ENTRY_NECROZMA[];
extern const u8 DEX_ENTRY_MAGEARNA[];
extern const u8 DEX_ENTRY_MARSHADOW[];
extern const u8 DEX_ENTRY_POIPOLE[];
extern const u8 DEX_ENTRY_NAGANADEL[];
extern const u8 DEX_ENTRY_STAKATAKA[];
extern const u8 DEX_ENTRY_BLACEPHALON[];
extern const u8 DEX_ENTRY_ZERAORA[];
extern const u8 DEX_ENTRY_MELTAN[];
extern const u8 DEX_ENTRY_MELMETAL[];
extern const u8 DEX_ENTRY_GROOKEY[];
extern const u8 DEX_ENTRY_THWACKEY[];
extern const u8 DEX_ENTRY_RILLABOOM[];
extern const u8 DEX_ENTRY_SCORBUNNY[];
extern const u8 DEX_ENTRY_RABOOT[];
extern const u8 DEX_ENTRY_CINDERACE[];
extern const u8 DEX_ENTRY_SOBBLE[];
extern const u8 DEX_ENTRY_DRIZZILE[];
extern const u8 DEX_ENTRY_INTELEON[];
extern const u8 DEX_ENTRY_SKWOVET[];
extern const u8 DEX_ENTRY_GREEDENT[];
extern const u8 DEX_ENTRY_ROOKIDEE[];
extern const u8 DEX_ENTRY_CORVISQUIRE[];
extern const u8 DEX_ENTRY_CORVIKNIGHT[];
extern const u8 DEX_ENTRY_BLIPBUG[];
extern const u8 DEX_ENTRY_DOTTLER[];
extern const u8 DEX_ENTRY_ORBEETLE[];
extern const u8 DEX_ENTRY_NICKIT[];
extern const u8 DEX_ENTRY_THIEVUL[];
extern const u8 DEX_ENTRY_GOSSIFLEUR[];
extern const u8 DEX_ENTRY_ELDEGOSS[];
extern const u8 DEX_ENTRY_WOOLOO[];
extern const u8 DEX_ENTRY_DUBWOOL[];
extern const u8 DEX_ENTRY_CHEWTLE[];
extern const u8 DEX_ENTRY_DREDNAW[];
extern const u8 DEX_ENTRY_YAMPER[];
extern const u8 DEX_ENTRY_BOLTUND[];
extern const u8 DEX_ENTRY_ROLYCOLY[];
extern const u8 DEX_ENTRY_CARKOL[];
extern const u8 DEX_ENTRY_COALOSSAL[];
extern const u8 DEX_ENTRY_APPLIN[];
extern const u8 DEX_ENTRY_FLAPPLE[];
extern const u8 DEX_ENTRY_APPLETUN[];
extern const u8 DEX_ENTRY_SILICOBRA[];
extern const u8 DEX_ENTRY_SANDACONDA[];
extern const u8 DEX_ENTRY_CRAMORANT[];
extern const u8 DEX_ENTRY_ARROKUDA[];
extern const u8 DEX_ENTRY_BARRASKEWDA[];
extern const u8 DEX_ENTRY_TOXEL[];
extern const u8 DEX_ENTRY_TOXTRICITY[];
extern const u8 DEX_ENTRY_SIZZLIPEDE[];
extern const u8 DEX_ENTRY_CENTISKORCH[];
extern const u8 DEX_ENTRY_CLOBBOPUS[];
extern const u8 DEX_ENTRY_GRAPPLOCT[];
extern const u8 DEX_ENTRY_SINISTEA[];
extern const u8 DEX_ENTRY_POLTEAGEIST[];
extern const u8 DEX_ENTRY_HATENNA[];
extern const u8 DEX_ENTRY_HATTREM[];
extern const u8 DEX_ENTRY_HATTERENE[];
extern const u8 DEX_ENTRY_IMPIDIMP[];
extern const u8 DEX_ENTRY_MORGREM[];
extern const u8 DEX_ENTRY_GRIMMSNARL[];
extern const u8 DEX_ENTRY_OBSTAGOON[];
extern const u8 DEX_ENTRY_PERRSERKER[];
extern const u8 DEX_ENTRY_CURSOLA[];
extern const u8 DEX_ENTRY_SIRFETCHD[];
extern const u8 DEX_ENTRY_MR_RIME[];
extern const u8 DEX_ENTRY_RUNERIGUS[];
extern const u8 DEX_ENTRY_MILCERY[];
extern const u8 DEX_ENTRY_ALCREMIE_STRAWBERRY[];
extern const u8 DEX_ENTRY_FALINKS[];
extern const u8 DEX_ENTRY_PINCURCHIN[];
extern const u8 DEX_ENTRY_SNOM[];
extern const u8 DEX_ENTRY_FROSMOTH[];
extern const u8 DEX_ENTRY_STONJOURNER[];
extern const u8 DEX_ENTRY_EISCUE[];
extern const u8 DEX_ENTRY_INDEEDEE[];
extern const u8 DEX_ENTRY_MORPEKO[];
extern const u8 DEX_ENTRY_CUFANT[];
extern const u8 DEX_ENTRY_COPPERAJAH[];
extern const u8 DEX_ENTRY_DRACOZOLT[];
extern const u8 DEX_ENTRY_ARCTOZOLT[];
extern const u8 DEX_ENTRY_DRACOVISH[];
extern const u8 DEX_ENTRY_ARCTOVISH[];
extern const u8 DEX_ENTRY_DURALUDON[];
extern const u8 DEX_ENTRY_DREEPY[];
extern const u8 DEX_ENTRY_DRAKLOAK[];
extern const u8 DEX_ENTRY_DRAGAPULT[];
extern const u8 DEX_ENTRY_ZACIAN[];
extern const u8 DEX_ENTRY_ZAMAZENTA[];
extern const u8 DEX_ENTRY_ETERNATUS[];
extern const u8 DEX_ENTRY_KUBFU[];
extern const u8 DEX_ENTRY_URSHIFU_SINGLE[];
extern const u8 DEX_ENTRY_ZARUDE[];
extern const u8 DEX_ENTRY_REGIELEKI[];
extern const u8 DEX_ENTRY_REGIDRAGO[];
extern const u8 DEX_ENTRY_GLASTRIER[];
extern const u8 DEX_ENTRY_SPECTRIER[];
extern const u8 DEX_ENTRY_CALYREX[];

extern const u8 DEX_ENTRY_RATTATA_A[];
extern const u8 DEX_ENTRY_RATICATE_A[];
extern const u8 DEX_ENTRY_RAICHU_A[];
extern const u8 DEX_ENTRY_SANDSHREW_A[];
extern const u8 DEX_ENTRY_SANDSLASH_A[];
extern const u8 DEX_ENTRY_VULPIX_A[];
extern const u8 DEX_ENTRY_NINETALES_A[];
extern const u8 DEX_ENTRY_DIGLETT_A[];
extern const u8 DEX_ENTRY_DUGTRIO_A[];
extern const u8 DEX_ENTRY_MEOWTH_A[];
extern const u8 DEX_ENTRY_MEOWTH_G[];
extern const u8 DEX_ENTRY_PERSIAN_A[];
extern const u8 DEX_ENTRY_GEODUDE_A[];
extern const u8 DEX_ENTRY_GRAVELER_A[];
extern const u8 DEX_ENTRY_GOLEM_A[];
extern const u8 DEX_ENTRY_PONYTA_G[];
extern const u8 DEX_ENTRY_RAPIDASH_G[];
extern const u8 DEX_ENTRY_SLOWPOKE_G[];
extern const u8 DEX_ENTRY_SLOWBRO_G[];
extern const u8 DEX_ENTRY_FARFETCHD_G[];
extern const u8 DEX_ENTRY_GRIMER_A[];
extern const u8 DEX_ENTRY_MUK_A[];
extern const u8 DEX_ENTRY_EXEGGUTOR_A[];
extern const u8 DEX_ENTRY_MAROWAK_A[];
extern const u8 DEX_ENTRY_WEEZING_G[];
extern const u8 DEX_ENTRY_MR_MIME_G[];
extern const u8 DEX_ENTRY_ARTICUNO_G[];
extern const u8 DEX_ENTRY_ZAPDOS_G[];
extern const u8 DEX_ENTRY_MOLTRES_G[];
extern const u8 DEX_ENTRY_SLOWKING_G[];
extern const u8 DEX_ENTRY_CORSOLA_G[];
extern const u8 DEX_ENTRY_ZIGZAGOON_G[];
extern const u8 DEX_ENTRY_LINOONE_G[];
extern const u8 DEX_ENTRY_DARUMAKA_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G_ZEN[];
extern const u8 DEX_ENTRY_YAMASK_G[];
extern const u8 DEX_ENTRY_STUNFISK_G[];
extern const u8 DEX_ENTRY_ZYGARDE_10[];
extern const u8 DEX_ENTRY_ZYGARDE_COMPLETE[];
extern const u8 DEX_ENTRY_ORICORIO_Y[];
extern const u8 DEX_ENTRY_ORICORIO_P[];
extern const u8 DEX_ENTRY_ORICORIO_S[];
extern const u8 DEX_ENTRY_LYCANROC_N[];
extern const u8 DEX_ENTRY_LYCANROC_DUSK[];
extern const u8 DEX_ENTRY_WISHIWASHI_S[];
extern const u8 DEX_ENTRY_NECROZMA_DUSK_MANE[];
extern const u8 DEX_ENTRY_NECROZMA_DAWN_WINGS[];
extern const u8 DEX_ENTRY_NECROZMA_ULTRA[];
extern const u8 DEX_ENTRY_CRAMORANT_GULPING[];
extern const u8 DEX_ENTRY_CRAMORANT_GORGING[];
extern const u8 DEX_ENTRY_TOXTRICITY_LOW_KEY[];
extern const u8 DEX_ENTRY_SINISTEA_CHIPPED[];
extern const u8 DEX_ENTRY_POLTEAGEIST_CHIPPED[];
extern const u8 DEX_ENTRY_ALCREMIE_BERRY[];
extern const u8 DEX_ENTRY_ALCREMIE_CLOVER[];
extern const u8 DEX_ENTRY_ALCREMIE_FLOWER[];
extern const u8 DEX_ENTRY_ALCREMIE_LOVE[];
extern const u8 DEX_ENTRY_ALCREMIE_RIBBON[];
extern const u8 DEX_ENTRY_ALCREMIE_STAR[];
extern const u8 DEX_ENTRY_EISCUE_NOICE[];
extern const u8 DEX_ENTRY_INDEEDEE_FEMALE[];
extern const u8 DEX_ENTRY_MORPEKO_HANGRY[];
extern const u8 DEX_ENTRY_ZACIAN_CROWNED[];
extern const u8 DEX_ENTRY_ZAMAZENTA_CROWNED[];
extern const u8 DEX_ENTRY_ETERNATUS_ETERNAMAX[];
extern const u8 DEX_ENTRY_URSHIFU_RAPID[];
extern const u8 DEX_ENTRY_CALYREX_ICE_RIDER[];
extern const u8 DEX_ENTRY_CALYREX_DARK_RIDER[];
